### ISSUE TITLE
Unsubs#Offers (unsub instance creation and typeform callback)

### ISSUE THREAD

**Issue by db0sch** [Llanowars/fleeme#29]
Typeform takes time to respond and send the unsub infos.
So we might upload the offers page before having an unsub instance... => 500 ERROR.

We have to wait for Typeform.

Possible solution : 
1/ ActionCable : with websocket, load the offers page, with a spinner. Once we have the unsub instance, we send the links, and insert them inside the page, so that the user can click on it.
2/ bg job and sidekiq : If ActionCable is not suitable for this, use Background Job, Redis and Sidekiq.

**Comment by juliends** [comment]
The instance of unsub is now created and saved when the typeform is launched
The webhook callback updates the unsub solving this issue
